### PR TITLE
replace `redis-async` with `redis` crate

### LINKED ISSUE #29: Connect to password protected redis
Maybe it is just me, but I can not find a place to config password for Redis backend in actix-redis, so I guess I will have to manually send AUTH password every time? 

Thanks.

### PR DESCRIPTION
**Pull request by mb1986**
Hi, I've replaced `redis-async` with `redis` crate what simplifies some parts of the code and gives new features like Unix socket connection, redis authentication and db selection.

Regards :)

Resolves issues #29, #15 and prs #19, #17.

### CODE REVIEW

**Comment by JohnTitor** [comment]
The change includes breaking changes. cc: @actix/core

**Comment by fafhrd91** [comment]
i am planing to rewrite actix-redis with service architecture. i am not sure if it is good idea to switch to redis crate

**Comment by mb1986** [comment]
I am not insisting on merging this PR. I did it because I need such functionalities and thought that maybe you will be interested :) Using `redis` crate was the easiest way for me. If you know how to do it better I will be happy to see your approach. By now I will be using what I have ;)
Thx for the crate :)

**Comment by JohnTitor** [comment]
Hey, we've been migrating this repository into https://github.com/actix/actix-extras so could you re-open this there? Closing for being archived.

**Pull request closed without merging**
