### PR TITLE
Remove client cookies and redis records when a session is empty

### PR DESCRIPTION
**Pull request by ourhut**
When a session state has been cleared and therefore has no entries, remove the session from the redis instance and clear the client cookie.

Extend testcase to test redis DEL command

Ignore the rls*.log files being generated on my development client.

### CODE REVIEW

**Review by Dowwie — COMMENTED** [review]
A session has multiple roles.  It isn't only a store: https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Session_Management_Cheat_Sheet.md

Purging a session from cookie/redis when there is no state disregards a session's other uses

**Comment by ourhut** [comment]
> A session has multiple roles. It isn't only a store: https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Session_Management_Cheat_Sheet.md
> 
> Purging a session from cookie/redis when there is no state disregards a session's other uses

Thank you for the document, I hadn't seen that before and it was interesting. It didn't however clarify for me a scenario where retaining a session when there is no longer state is preferable to creating a new session when state returns. I'd be interested in understanding this case.

In my use case I'm using actix-redis for authentication and access control. When a client logs out I want to no longer us that session. If the client logs back in, I want the new login to use a new session, not reuse an earlier session.

Without understanding the scenario where retaining a session across the empty state, I'm unclear if you are saying forgetting a session is always undesirable, or sometimes undesirable.

Is there an alternative you would suggest for my scenario? Would changing this PR to be an optional (non-default) behavior make sense instead?

**Comment by Dowwie** [comment]
It seems like you're heading in the right direction with your work but you're trying to advance an opinionated implementation (purge empty sessions) into an open source project that has to appeal to general use.  How you use state is implementation-specific.  When you roll session-keys, too.  In one system design, a user can log in and start a session yet no state exists.  How is this so?  Different caching schema/strategy.  Maybe user credentials and access control are cached but not in the session store itself?  Maybe sessions are use to store non-security related state?  That depends on one's preference.

I basically wrote what you are now and ended up managing my own modules for my work when it was rejected for general use last year.  I use sessions for storing state among requests.  

I am still lobbying to make session key cycling a general feature, which would help you achieve your login/logout goals.  Maybe @fafhrd91 will warm up to the idea as more people ask for this functionality (except for purging on empty state, which is very much yours).

Let's see what @fafhrd91 says about all of this, though, as this is ultimately his call..

**Comment by ourhut** [comment]
Another option would be to modify Session to add "Abandon" or "Forget" as a method at that layer, so I can use that later in my middleware on logout. Would that be better aligned with the general usage and design goals?

**Comment by Dowwie** [comment]
@ourhut FYI:  finally merged changes to support purging cookie + session state, in 0.6.  A release is imminent.

**Pull request closed without merging**
