### PR TITLE
added some documentation

### PR DESCRIPTION
**Pull request by ava57r**
#2

### CODE REVIEW

**Review by fafhrd91 — APPROVED** [review]

**Comment by fafhrd91** [comment]
lgtm

do you have merge permission?

**Comment by ava57r** [comment]
lgtm ?

do you offer to send commits directly actix-redis?

**Comment by fafhrd91** [comment]
lgtm = looks good to me, and I approved PR
if you have merge permission, you can merge this pr

**Comment by ava57r** [comment]
I have permission to merge.

**Pull request merged**
